server:
  port: ${PORT:8000}

# define the destination to which the input MessageChannel should be bound
# spring.cloud.stream.bindings.input.destination = reservations

# ensures 1 node in a group gets message (point-to-point, not a broadcast)
# spring.cloud.stream.bindings.input.group = reservations-group

# ensure that the Q is durable
# spring.cloud.stream.bindings.input.durableSubscription = true

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
          group: reservations_group
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /